# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ptype', models.CharField(max_length=30)),
                ('Pid', models.IntegerField()),
                ('Pstate', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AlterField(
            model_name='jumachine',
            name='jid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='process',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='oj.Jumachine', to_field='jid'),
        ),
    ]
