# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_auto_20160728_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='Pid',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='Pstate',
            new_name='pstate',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='Ptype',
            new_name='ptype',
        ),
    ]
